# Usa a imagem base oficial do Node.js
FROM node:18-alpine

# Define o diretório de trabalho dentro do container
WORKDIR /app

# Copia os arquivos de dependência do seu projeto para o container
COPY package*.json ./

# Instala as dependências de produção
RUN npm ci --only=production

# Copia o restante do código da aplicação
COPY . .

# Constrói a aplicação (gera os arquivos estáticos para produção)
RUN npm run build

# Expõe a porta em que a aplicação será executada
EXPOSE 3000

# Define o comando para iniciar a aplicação
CMD ["npm", "start"]
